#!/bin/bash
set -e

apt update
DEBIAN_FRONTEND=noninteractive apt install -y tmux git ripgrep fd-find build-essential unzip luarocks

# fd
# ln -s $(which fdfind) ~/.local/bin/fd

# lazygit
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf /tmp/lazygit.tar.gz -C /tmp/
install /tmp/lazygit /usr/local/bin

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# symlinks
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/lazygit" "$XDG_CONFIG_HOME"/lazygit

curl -Lo /tmp/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
rm -rf /opt/nvim
tar -C /opt -xzf /tmp/nvim-linux64.tar.gz
echo 'export PATH="$PATH:/opt/nvim-linux64/bin"' >>"$HOME"/.bashrc

# node
echo "Installing Node"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
# download and install Node.js (you may need to restart the terminal)
export NVM_DIR="$HOME/.config/nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
nvm install 20

# echo "Installing yarn"
# npm install --global yarn

# #luarocks
# curl -Lo /tmp/lua-5.3.5.tar.gz http://www.lua.org/ftp/lua-5.3.5.tar.gz
# tar -zxf /tmp/lua-5.3.5.tar.gz -C /tmp
# cd /tmp/lua-5.3.5
# make linux test
# make install
